name: 'Synchronize'

on:
  workflow_dispatch:
  schedule:
    - cron: '*/10 * * * *'

jobs:
  Synchronize_integrations:
    runs-on: ubuntu-latest
    timeout-minutes: 0.3
    steps:
      - run: |
          curl -X POST 'https://pipesheet.vercel.app/api/synchronize' -H "Accept: */*"
