name: 'Synchronize'

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'

jobs:
  Synchronize_integrations:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -X POST 'https://pipesheet-akpigzx8t-admincjr.vercel.app/api/synchronize' -H "Accept: */*"
